Repository muqa-org/zazelenimo, pull requests merged in 2024-08, with the labels that each got.

#22 Creating homepage
  apps/platform/.prettierrc.json
  apps/platform/package.json
  apps/platform/public/images/icons/icon-top-right-arrow.svg
  apps/platform/public/images/icons/icon-yes.svg
  apps/platform/public/images/icons/socials/icon-discord.svg
  apps/platform/public/images/icons/socials/icon-github.svg
  apps/platform/public/images/icons/socials/icon-telegram.svg
  apps/platform/public/images/icons/socials/icon-x.svg
  apps/platform/public/images/logo/logo-muqa.svg
  apps/platform/src/app/WalletStatus.tsx
  apps/platform/src/app/components/Button.tsx
  apps/platform/src/app/components/RoundPhase.tsx
  apps/platform/src/app/components/common/Icons.tsx
  apps/platform/src/app/components/common/Images.tsx
  apps/platform/src/app/components/common/Socials.tsx
  apps/platform/src/app/components/footer/FooterLinks.tsx
  apps/platform/src/app/components/footer/footer.tsx
  apps/platform/src/app/components/homepage/HomepageIntro.tsx
  apps/platform/src/app/components/homepage/HomepageRoundBoxes.tsx
  apps/platform/src/app/header.tsx
  apps/platform/src/app/layout.tsx
  apps/platform/src/app/page.tsx
  apps/platform/tailwind.config.ts
  pnpm-lock.yaml
Labels: enhancement

#26 feature: introduce MuqaConnectButton
  apps/platform/src/app/WalletStatus.tsx
  apps/platform/src/app/components/Button.tsx
  apps/platform/src/app/components/MuqaConnectButton.tsx
  apps/platform/src/app/components/homepage/HomepageIntro.tsx
  apps/platform/src/app/header.tsx
  package.json
  packages/kit/src/index.tsx
  packages/kit/src/strategies/index.ts
  packages/kit/src/wagmi/index.ts
Labels: needs review

#49 feature: add database
  apps/platform/package.json
  apps/platform/src/app/[chainId]/page.tsx
  apps/platform/src/app/components/homepage/HomepageIntro.tsx
  apps/platform/src/app/components/homepage/HomepageRoundBoxes.tsx
  apps/platform/src/app/components/projects/ProjectList.tsx
  apps/platform/src/app/components/projects/ProjectsSidebar.tsx
  apps/platform/src/app/components/projects/ProjectsSidebarPhases.tsx
  apps/platform/src/app/page.tsx
  apps/platform/src/app/types/round.ts
  apps/platform/tsconfig.json
  packages/db/.gitignore
  packages/db/index.ts
  packages/db/lib/db.ts
  packages/db/package.json
  packages/db/prisma/migrations/20240814200352_init/migration.sql
  packages/db/prisma/migrations/20240814201206_lowercase_user_fields/migration.sql
  packages/db/prisma/migrations/20240814201721_add_user_timestamps/migration.sql
  packages/db/prisma/migrations/20240814214946_add_round_phase/migration.sql
  packages/db/prisma/migrations/migration_lock.toml
  packages/db/prisma/schema.prisma
  packages/db/prisma/seed.ts
  packages/db/prisma/seeds/round-phases.ts
  packages/db/tsconfig.json
  packages/eslint-config/next.js
  packages/eslint-config/package.json
  pnpm-lock.yaml
Labels: needs review

#50 Feat responsive design
  apps/platform/messages/en.json
  apps/platform/messages/hr.json
  apps/platform/public/images/icons/icon-arrow-down copy.svg
  apps/platform/public/images/icons/icon-arrow-down-gray.svg
  apps/platform/public/images/icons/icon-arrow-down-green.svg
  apps/platform/public/images/icons/icon-close-gray.svg
  apps/platform/public/images/icons/icon-menu.svg
  apps/platform/src/app/Header.tsx
  apps/platform/src/app/components/Banner.tsx
  apps/platform/src/app/components/Container.tsx
  apps/platform/src/app/components/LanguageSwitcher.tsx
  apps/platform/src/app/components/Navigation.tsx
  apps/platform/src/app/components/common/Icons.tsx
  apps/platform/src/app/components/footer/FooterLinks.tsx
  apps/platform/src/app/components/homepage/HomepageAbout.tsx
  apps/platform/src/app/components/homepage/HomepageBanner.tsx
  apps/platform/src/app/components/homepage/HomepageEligibleProjects.tsx
  apps/platform/src/app/components/homepage/HomepageExampleProject.tsx
  apps/platform/src/app/components/homepage/HomepageFAQ.tsx
  apps/platform/src/app/components/homepage/HomepageFundsAllocated.tsx
  apps/platform/src/app/components/homepage/HomepageHero.tsx
  apps/platform/src/app/components/homepage/HomepageIntro.tsx
  apps/platform/src/app/components/homepage/HomepageStats.tsx
  apps/platform/tailwind.config.ts
Labels: wip, needs review

#52 feat: projects list
  apps/platform/.env.example
  apps/platform/messages/en.json
  apps/platform/messages/hr.json
  apps/platform/package.json
  apps/platform/public/images/icons/icon-cart-green.svg
  apps/platform/public/images/icons/icon-cart-white.svg
  apps/platform/public/images/icons/icon-checked.svg
  apps/platform/public/images/icons/icon-marker-zero.svg
  apps/platform/public/images/icons/icon-marker.svg
  apps/platform/public/images/icons/socials/icon-facebook-white.svg
  apps/platform/public/images/icons/socials/icon-x-white.svg
  apps/platform/src/app/Header.tsx
  apps/platform/src/app/[chainId]/page.tsx
  apps/platform/src/app/[chainId]/projects/[projectId]/page.tsx
  apps/platform/src/app/components/Navigation.tsx
  apps/platform/src/app/components/cart/AddToCart.tsx
  apps/platform/src/app/components/common/Icons.tsx
  apps/platform/src/app/components/homepage/HomepageAbout.tsx
  apps/platform/src/app/components/project/ProjectCard.tsx
  apps/platform/src/app/components/project/ProjectDetails.tsx
  apps/platform/src/app/components/project/ProjectMap.tsx
  apps/platform/src/app/components/project/ProjectMapInfoWindow.tsx
  apps/platform/src/app/components/project/ProjectSidebar.tsx
  apps/platform/src/app/components/project/ProjectSocialIcons.tsx
  apps/platform/src/app/components/projects/ProjectList.tsx
  apps/platform/src/app/components/projects/ProjectListHeader.tsx
  apps/platform/src/app/components/projects/ProjectListMap.tsx
  apps/platform/src/app/components/projects/ProjectListTable.tsx
  apps/platform/src/app/components/projects/ProjectsSidebar.tsx
  apps/platform/src/app/config/config.ts
  apps/platform/src/app/globals.css
  apps/platform/src/app/helpers/projectHelper.ts
  apps/platform/tailwind.config.ts
  pnpm-lock.yaml
Labels: needs review

#59 Feature/cart page
  apps/platform/messages/en.json
  apps/platform/messages/hr.json
  apps/platform/public/images/icons/icon-alert.svg
  apps/platform/public/images/icons/icon-party.svg
  apps/platform/public/images/icons/icon-trash.svg
  apps/platform/src/app/Header.tsx
  apps/platform/src/app/cart/completed/page.tsx
  apps/platform/src/app/cart/page.tsx
  apps/platform/src/app/components/cart/AddToCart.tsx
  apps/platform/src/app/components/cart/CartProjectCard.tsx
  apps/platform/src/app/components/common/Icons.tsx
  apps/platform/src/app/layout.tsx
  apps/platform/src/app/types/cart.ts
Labels: needs review

#64 Fix translation inside cart submission
  apps/platform/messages/en.json
Labels: needs review

#66 Fix and resolving homepage content
  apps/platform/messages/en.json
  apps/platform/messages/hr.json
  apps/platform/src/app/components/Navigation.tsx
  apps/platform/src/app/components/homepage/HomepageFAQ.tsx
  apps/platform/src/app/config/config.ts
Labels: wip

#65 Fixinf typos and code improvement on project list
  apps/platform/messages/en.json
  apps/platform/messages/hr.json
  apps/platform/src/app/[chainId]/page.tsx
  apps/platform/src/app/components/project/ProjectCard.tsx
  apps/platform/src/app/components/project/ProjectMap.tsx
  apps/platform/src/app/components/project/ProjectMapInfoWindow.tsx
  apps/platform/src/app/components/project/ProjectSidebar.tsx
  apps/platform/src/app/components/projects/ProjectList.tsx
  apps/platform/src/app/components/projects/ProjectListHeader.tsx
  apps/platform/src/app/components/projects/ProjectListMap.tsx
  apps/platform/src/app/config/config.ts
  apps/platform/src/app/helpers/projectHelper.ts
  apps/platform/tailwind.config.ts
Labels: needs review

#68 Fix/production landing page, part #2
  apps/platform/messages/en.json
  apps/platform/messages/hr.json
  apps/platform/public/images/icons/socials/icon-facebook.svg
  apps/platform/src/app/Header.tsx
  apps/platform/src/app/components/Banner.tsx
  apps/platform/src/app/components/Navigation.tsx
  apps/platform/src/app/components/NotificationBar.tsx
  apps/platform/src/app/components/common/Icons.tsx
  apps/platform/src/app/components/common/Socials.tsx
  apps/platform/src/app/components/footer/FooterLinks.tsx
  apps/platform/src/app/components/homepage/HomepageIntro.tsx
  apps/platform/src/app/components/projects/ProjectsSidebar.tsx
  apps/platform/src/app/config/index.ts
Labels: needs review

#70 fix/croatian is now default language
  apps/platform/src/app/api/locale/route.ts
  apps/platform/src/app/components/LanguageSwitcher.tsx
  apps/platform/src/i18n.ts
Labels: needs review
